### ISSUE TITLE
ImportError: No module named 'multitask'

### ISSUE THREAD

**Issue by degibenz** [mosquito/crew#11]
(env34)MacBook-Pro-Admin:brainauth degibenz$ ./tornado_app.py 
Traceback (most recent call last):
  File "./tornado_app.py", line 15, in <module>
    from crew.master.tornado import Client as crew_client
  File "/Users/degibenz/project/env34/lib/python3.4/site-packages/crew/master/tornado/**init**.py", line 1, in <module>
    from .client import Client
  File "/Users/degibenz/project/env34/lib/python3.4/site-packages/crew/master/tornado/client.py", line 16, in <module>
    from multitask import MultitaskCall
ImportError: No module named 'multitask'

**Comment by Pehat** [comment]
@degibenz Let me guess. You're using Python 3, aren't you?

`crew` contains a handful of relative imports which fail in Python 3 due to new importing system. @mosquito , are those relative imports contain some magic or they can be successfully replaced with absolute imports (if you don't mind, of course)?

**Comment by Pehat** [comment]
@degibenz , version 0.9.1 is available from PyPI. Try to upgrade and test again.
